#version: '3'

#services:
#  app:
#    build:
#      context: .
#    ports:
#      - "5000:5000"
#    volumes:
#      - ./app:/app
#    command: >
#      sh -c "set FLASK_APP=app.py && python app.py"
